export const SIGNUP = "SIGNUP";

export const ERROR = "ERROR";
export const SUCCESS = "SUCCESS";

export const GET_CONVERSATION_USER = "GET_CONVERSATION_USER";

export const GET_MESSENAGE_THEARER = "GET_MESSENAGE_THEARER";
export const ERROR_MESSENAGE_THEARER = "ERROR_MESSENAGE_THEARER";

export const CONFRIM_FRIEND = "CONFRIM_FRIEND";
export const LIST_FRIEND = "LIST_FRIEND";

export const LIST_REQEST_ADD_FRIEND = "LIST_REQEST_ADD_FRIEND ";
export const LIST_SEND_RESQEST_ADD_FRIEND = "LIST_SEND_RESQEST_ADD_FRIEND";

export const RESUTL_SEARCH = "RESUTL_SEARCH";

export const SHOW_ADD_FRIEND = "SHOW_ADD_FRIEND";
export const LOSE_ADD_FRIEND = "LOSE_ADD_FRIEND";

export const SHOW_BLUR = "SHOW_BLUR";
export const LOSE_BLUR = "LOSE_BLUR";

export const SHOW_UPDATE_INFO = "SHOW_UPDATE_INFO";
export const LOSE_UPDATE_INFO = "LOSE_UPDATE_INFO";

export const DELETE_THEATER_SUCCESS = "DELETE_THEATER_SUCCESS";
export const DELETE_THEATER_ERROR = "DELETE_THEATER_ERROR";

export const CREATE_THEATER_SUCCESS = "CREATE_THEATER_SUCCESS";
export const CREATE_THEATER_ERROR = "CREATE_THEATER_ERROR";
