export const SIGNUP = "SIGNUP";

export const ERROR = "ERROR";
export const SUCCESS = "SUCCESS";

// export const SUCCESS_All_USER = "SUCCESS_All_USER";
export const GET_CONVERSATION_USER = "GET_CONVERSATION_USER";

export const GET_MESSENAGE_THEARER = "GET_MESSENAGE_THEARER";
export const ERROR_MESSENAGE_THEARER = "ERROR_MESSENAGE_THEARER";

export const CONFRIM_FRIEND = "CONFRIM_FRIEND";
export const LIST_FRIEND = "LIST_FRIEND";

export const RESUTL_SEARCH = "RESUTL_SEARCH";

export const SHOW_ADD_FRIEND = "SHOW_ADD_FRIEND";
export const LOSE_ADD_FRIEND = "LOSE_ADD_FRIEND";

export const SHOW_BLUR = "SHOW_BLUR";
export const LOSE_BLUR = "LOSE_BLUR";
